# Generated by Django 5.2.5 on 2025-08-27 21:41

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_follow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["user", "created_at"], name="social_albu_user_id_584c05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["visibility", "created_at"],
                name="social_albu_visibil_a017e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="social_albu_is_publ_5cce84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "created_at"], name="social_comm_post_id_460cff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "created_at"], name="social_comm_user_id_261a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "status", "created_at"],
                name="social_foll_followe_9459ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["followed", "status", "created_at"],
                name="social_foll_followe_b9cfbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["post", "created_at"], name="social_like_post_id_c2bda0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["user", "created_at"], name="social_like_user_id_b6a081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["album", "created_at"], name="social_phot_album_i_d2dff6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["user", "created_at"], name="social_post_user_id_4bb736_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "created_at"],
                name="social_post_visibil_2fa219_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="social_post_is_publ_77d235_idx",
            ),
        ),
    ]
