# Generated by Django 5.2.5 on 2025-08-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "social",
            "0004_like_created_at_album_social_albu_user_id_584c05_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="album",
            name="social_albu_user_id_584c05_idx",
        ),
        migrations.RemoveIndex(
            model_name="album",
            name="social_albu_visibil_a017e4_idx",
        ),
        migrations.RemoveIndex(
            model_name="album",
            name="social_albu_is_publ_5cce84_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="social_comm_post_id_460cff_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="social_comm_user_id_261a35_idx",
        ),
        migrations.RemoveIndex(
            model_name="follow",
            name="social_foll_followe_9459ca_idx",
        ),
        migrations.RemoveIndex(
            model_name="follow",
            name="social_foll_followe_b9cfbc_idx",
        ),
        migrations.RemoveIndex(
            model_name="like",
            name="social_like_post_id_c2bda0_idx",
        ),
        migrations.RemoveIndex(
            model_name="like",
            name="social_like_user_id_b6a081_idx",
        ),
        migrations.RemoveIndex(
            model_name="photo",
            name="social_phot_album_i_d2dff6_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="social_post_user_id_4bb736_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="social_post_visibil_2fa219_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="social_post_is_publ_77d235_idx",
        ),
        migrations.RemoveField(
            model_name="like",
            name="created_at",
        ),
    ]
