# Generated by Django 5.2.5 on 2025-08-28 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "social",
            "0004_like_created_at_album_social_albu_user_id_584c05_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Comment cannot be empty."
                    ),
                    django.core.validators.MaxLengthValidator(
                        1000, "Comment cannot exceed 1000 characters."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        5000, "Post content cannot exceed 5000 characters."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Title must be at least 5 characters long."
                    ),
                    django.core.validators.MaxLengthValidator(
                        200, "Title cannot exceed 200 characters."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("followers", "Followers only"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=16,
            ),
        ),
    ]
