# Generated by Django 5.2.5 on 2025-09-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_remove_album_social_albu_user_id_584c05_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
