# Generated by Django 5.2.5 on 2025-08-28 12:30

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_albumcomment_albumlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="file",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.photo_file_upload_to
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.photo_thumb_upload_to
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.post_image_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
