# Generated by Django 5.2.5 on 2025-08-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_photo_file_photo_thumbnail_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("followers", "Followers only"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=16,
            ),
        ),
    ]
