# Generated by Django 5.2.5 on 2025-08-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("color", models.CharField(default="#6b7280", max_length=16)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="todoitem",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="todos.todopriority",
            ),
        ),
    ]
