# Generated by Django 5.2.5 on 2025-08-27 20:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_user_is_private"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the user account was created",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False, help_text="Whether email has been verified"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(
                default=False, help_text="Whether phone number has been verified"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends only"),
                    ("private", "Private"),
                ],
                default="public",
                help_text="Privacy level for profile information",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the user account was last updated",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="User's bio or description (max 2000 characters)",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="User's address (max 1000 characters)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                blank=True, help_text="Profile picture URL", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="User's full name",
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Full name must be at least 2 characters long."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                help_text="User's gender identity",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether account is active"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(
                default=False, help_text="Whether user has premium subscription"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(
                default=False, help_text="Whether user's profile is private"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number with country code",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="users_user_usernam_65d164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_premium"], name="users_user_is_prem_d1e871_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_private"], name="users_user_is_priv_c6e864_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="users_user_date_jo_064c8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="users_user_created_cf865c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["updated_at"], name="users_user_updated_cc7221_idx"
            ),
        ),
    ]
