# Generated by Django 5.2.5 on 2025-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options_user_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_usernam_65d164_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_email_6f2530_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_is_prem_d1e871_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_is_priv_c6e864_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_date_jo_064c8f_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_created_cf865c_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_updated_cc7221_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_privacy",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
