name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Backend deps
        working-directory: apps/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate OpenAPI schema
        working-directory: apps/backend
        run: |
          python manage.py spectacular --file ../../openapi.json

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Frontend deps
        working-directory: apps/frontend
        run: npm ci

      - name: Frontend build
        working-directory: apps/frontend
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            openapi.json
            apps/frontend/dist
